sudo: required
language: java
jdk: openjdk7

services: mysql

before_script:
- sudo mysql -e "USE mysql; UPDATE mysql.user SET user='acme-user', password=PASSWORD('ACME-Us3r-P@ssw0rd') WHERE user='root'; FLUSH PRIVILEGES;"
- sudo mysql -e "create database 'Acme-HandyWorker';"
- sudo mysql -e "create user 'acme-manager'@'%'	identified by password '*FDB8CD304EB2317D10C95D797A4BD7492560F55F';"
- sudo mysql -e "grant select, insert, update, delete on `Acme-HandyWorker`.* to 'acme-user'@'%';"
- sudo mysql -e "grant select, insert, update, delete, create, drop, references, index, alter, create temporary tables, lock tables, create view, create routine, alter routine, execute, trigger, show view on `Acme-HandyWorker`.* to 'acme-manager'@'%';"
- javac src/main/java/utilities/PopulateDatabase.java
- java src/main/java/utilities/PopulateDatabase

script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

addons:
  apt:
   sources:
    - mysql-5.7-trusty
   packages:
    - mysql-server
    - mysql-client
