sudo: required
language: java
jdk: openjdk7

services: mysql

before_script:
- mysql -e 'CREATE DATABASE Acme-HandyWorker;'
- sudo mysql -e "USE mysql; UPDATE mysql.user SET user='acme-user', password=PASSWORD('ACME-Us3r-P@ssw0rd') WHERE user='root'; FLUSH PRIVILEGES;"
- sudo mysql_upgrade
- sudo service mysql restart

script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
