sudo: required
language: java
jdk: openjdk7

services: mysql

before_script:
- sudo mysql -e "USE mysql; UPDATE mysql.user SET user='acme-user', password=PASSWORD('ACME-Us3r-P@ssw0rd') WHERE user='root'; FLUSH PRIVILEGES;"
- sudo mysql_upgrade
- sudo service mysql restart
- java src/main/java/utilities/PopulateDatabase.java

script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
